### ISSUE TITLE
User Story: Dynamic Navigation Bar

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#47]
As a **User**, when I click on a console in the landing page, **the main navigation bar dynamically changes** to reflect the selected console's branding, allowing me to **immerse myself in the selected console's environment**

# Acceptance Criteria:
- Acceptance Criteria 1: When a user selects a console from the navigation bar, the style, branding and links of the navigation bar dynamically update to match the chosen console's theme.
- Acceptance Criteria 2: Clicking on the branding on top, navigates the user back to the main landing page.
- Acceptance Criteria 3: Each console in the navigation bar has its distinct branding and design elements that are consistently displayed when that section is active.

# Tasks
- [x] Implement frontend logic to dynamically change the navbar's content.
- [x] Ensure the design updates upon console selection.
- [x] Implement logic to revert the top branding back to "Ludus Nexus" when the home icon is clicked.
- [x] Test the navbar on different screen sizes to ensure responsiveness.

**Comment by Julius-88** [comment]
Removal of the home icon was made after having observed the reference pages. It seems that none of them has this icon and instead rely on their branding to serve the same function.
