### ISSUE TITLE
User Story: Personalized Browsing

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#49]
As a **Registered User** I want to **have a personalized browsing experience based on my preferences** so that **I can quickly access my favorite consoles or recently viewed items**

# Acceptance Criteria:
- Acceptance Criteria 1: After logging in, users can see their favorite object highlighted.
- Acceptance Criteria 2: After logging in, users can see their recently viewed objects highlighted.
- Acceptance Criteria 3: After logging in, users can set an object as a favorite.

# Tasks
- [ ] Implement backend logic to capture and store user preferences.
- [ ] Integrate this personalized data into the users profile.
- [ ] Create UI components to display highlighted favorite and recently viewed items.
