### ISSUE TITLE
User Story: Navigation

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#52]
As a **User** I can **view the main navigation bar** so that **I can quickly find my way around the website**

# Acceptance Criteria:
- Acceptance Criteria 1: Navigation bar must be accessible on every page
- Acceptance Criteria 2: Navigation bar contains links to the Playstation, Xbox and Nintendo sections.
- Acceptance Criteria 3: Links are styled with their significant color and logo.
- Acceptance Criteria 4: Navigation bar includes interactive and recognizable icons for shopping cart and login.

# Tasks
- [x] Create the main navigation bar at the top of the page.
- [x] Create navigation links with respective console branding.
- [x] Create an icon for the shopping cart to the far right of the navbar.
- [x] Create an icon for the login button next to the shopping cart.
- [x] Ensure responsiveness across devices
