### ISSUE TITLE
User Story: Footer Contact information

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#59]
As a **User** I can **easily find and use the company's contact information in the footer,** so that **I can quickly reach out with any questions or concerns I might have.**

#Acceptance Criteria:
- Acceptance Criteria 1: The company contact information is located in the footer.
- Acceptance Criteria 2: Clicking on the email address initiates the process to send a message via a web form.

# Tasks
- [ ] Create a Contact Us section in the footer.
- [ ] Add the company's email address.
- [ ] Configure the email address to open a web form module. 
- [ ] Ensure the form and information is responsive and accessible on all devices.
