### ISSUE TITLE
User Story: Survey - User Interface

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#63]
As a **User** I can **easily access and take a quick survey on the website** so that **I can engage in an interactive way to find the perfect gift for my loved one.**

#Acceptance Criteria:
- Acceptance Criteria 1: Create a section for the survey underneath the news banner
- Acceptance Criteria 2: When clicking on the survey button it will open up a banner with interactive questions.

# Tasks
- [ ] Implement a survey section underneath the news banner.
- [ ] Implement a modal window that opens upon clicking a "Take Survey" button, displaying a series of user-friendly questions.
- [ ] Ensure the survey is intuitive and provides a seamless user experience.
