### ISSUE TITLE
User Story: Upcoming Events - User Interface

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#65]
As a **User** I want to **view an engaging and informative section on the website showcasing upcoming gaming events with essential details,** so that **I can easily track and plan to watch these events.**

#Acceptance Criteria:
- Acceptance Criteria 1: Create a section for Upcoming events, with each event's name, date and a live countdown timer.
- Acceptance Criteria 2: Each event listing includes a direct link to the event's official Twitch stream.
- Acceptance Criteria 3: It allows users to set reminders or receive notifications for events they are interested in.

# Tasks
- [ ] Implement a Upcoming Events section.
- [ ] Showcase the event name, date, countdown timer and twitch link.
- [ ] Implement functionality for users to set reminders or opt-in for notifications for specific events.
- [ ] Ensure it is responsive on all devices.
