### ISSUE TITLE
User Story: Upcoming Events - Functionality

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#66]
As a **User** I can **save the upcoming event I would like to see** so that **I can receive a notification when the event is going live.**

# Acceptance Criteria:
- Acceptance Criteria 1: It allows users to receive notifications for events they are interested in via email.

# Tasks
- [ ] Implement functionality for users to set reminders via email notification for the event chosen.
- [ ] Test functionality to see make sure it is working correctly.
- [ ] Add a confirmation for the user.
