### ISSUE TITLE
User Story: Console Pages

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#67]
As a **User** I can **click on my chosen console and be taken to said consoles page** so that **I can view everything that is related to my chosen console.**

# Acceptance Criteria:
- Acceptance Criteria 1: Upon clicking on a console name the user is brought to the chosen console page and can find related products. 
- Acceptance Criteria 2: The header text, font and color must change to the appropriate console.
- Acceptance Criteria 3: The sub-nav must be shown with the correct colors and fonts.

# Tasks
- [x] Create a page for Nintendo, Playstation and Xbox and make sure each is linked to the corresponding navbar button.
- [x] The sub-nav must be shown when choosing a console, otherwize be hidden.
- [x] Each sub-nav must display the correct color and font for the chosen console.
