### ISSUE TITLE
User Story: Console Pages - Product Shopping Cart

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#70]
As a **User** I can **add a product to my shopping cart while browsing** so that **I can collect everything I want and buy all the products at the same time.**

# Acceptance Criteria:
- Acceptance Criteria 1: A visible shopping cart icon should be present underneath each product to add the product to their shopping cart.
- Acceptance Criteria 2: Once the shopping cart icon is clicked, its color changes to indicate that the product has been added to the cart.
- Acceptance Criteria 3: Clicking on the shopping cart icon again, it should take the user to the shopping cart where the user can view, remove items, modify quantity or proceed to checkout.

# Tasks
- [ ] Implement a shopping cart icon for each product.
- [ ] Ensure the icon changes color upon being clicked to visually confirm the addition of the product to the cart.
- [ ] Ensure added products are accurately reflected in the shopping cart.
