### ISSUE TITLE
User Story: Wish List Page

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#72]
As a **User** I can **view all the products I have added to my wishlist** so that **I can quickly find them again when I wish to buy them and add them to my shopping cart.**

# Acceptance Criteria:
- Acceptance Criteria 1: A wish list page should be available from the users profile.
- Acceptance Criteria 2: Each product in the wish list should have an accompanying icon for removing the product from the list.
- Acceptance Criteria 3: A shopping cart icon should be present alongside each product which adds it to the shopping cart.

# Tasks
- [ ] Develop a wish list page that can be accessed from the user's profile.
- [ ] Integrate a shopping cart icon with each product on the wish list page, which adds to the item to the shopping cart.
- [ ] Include a remove button or icon with each product to allow users to remove products from their wish list.
