### ISSUE TITLE
User Story: Checkout

### ISSUE THREAD

**Issue by Julius-88** [Julius-88/ludus-nexus#74]
As a **User** I can **proceed to checkout to provide my shipping and payment information and confirm my order** so that **I can complete my purchase, receive immediate on-page confirmation and review my order on my account page.**

# Acceptance Criteria:
- Acceptance Criteria 1: Upon selecting 'Proceed to Checkout', the user is directed to a checkout page to enter shipping and then they are directed to the payment page where they can enter their payment details.
- Acceptance Criteria 2: After completing the purchase, the user receives an on-page confirmation on the transaction's success and their order details.
- Acceptance Criteria 3: Completed orders are saved in the user's account, providing a digital receipt and order history for future reference.

# Tasks
- [x] Develop a Checkout page with a form for the user to enter shipping and payment details.
- [x] Develop a Order Confirmation page displaying the details of the order.
- [x] Implement a 'Complete Order' button on the Checkout page that finalizes the transaction and directs the user to the Order Confirmation page.
- [x] Implement a return button on the payment page for easy navigation back to the shopping bag.
- [x] Implement a 'Adjust Order' button on the Checkout page, allowing users to return to the shopping cart for any last-minute changes.
- [x] Implement a feedback to the user if the purchase was successful or unsuccessful with a helpful message.
- [x] Save completed orders in the user's account to provide a digital receipt and order history.
